[package]
name = "telescope-fzf-native"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2"

[build-dependencies]
bindgen = "0.69"
cc = { version = "1.0", features = ["parallel"] }
pkg-config = "0.3"
